Added function "hightling_data"
ttricco/framalytics pull request #5
Opened 2024-05-16 17:42 UTC by TheFatalBlazer

Added a function, which given a dataframe, will highlight the paths accordingly. The columns must be the name of functions used by the fram model. Values must be 0 (absent) or 1 (present) for each. Paths will be highlighted based on the number of times both functions of a single curve have a value of 1 over all instances.

2024-05-22 16:26 UTC, ttricco requested changes

2024-05-22 16:26 UTC, ttricco commented on framalytics/fram.py
> +
We can avoid this inner loop by using pandas slicing and len().

`connection_value = len(data[(data[outputFn_name] == 1) & (data[toFn_name] == 1)])`

2024-05-22 16:26 UTC, ttricco commented on framalytics/FRAM_Visualizer.py
Add color as a param in the docstring.

2024-05-27 18:24 UTC, TheFatalBlazer commented
Updated Pull Request to include the most recent changes. This included updated documentation and minor error fixes.

2024-06-05 18:23 UTC, TheFatalBlazer reviewed
Added fnStyles to the figure, which alter the location of aspects based on a functions style. Currently all functions will share the style of the first function in the .xfmv file.

2024-06-05 19:20 UTC, ttricco approved these changes

2024-06-05 19:20 UTC, merged